// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: internal/server/proto/dirscanner.proto

package dirscanner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DirscannerClient is the client API for Dirscanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirscannerClient interface {
	Scan(ctx context.Context, in *DirScanRequest, opts ...grpc.CallOption) (*DirScanResponse, error)
}

type dirscannerClient struct {
	cc grpc.ClientConnInterface
}

func NewDirscannerClient(cc grpc.ClientConnInterface) DirscannerClient {
	return &dirscannerClient{cc}
}

func (c *dirscannerClient) Scan(ctx context.Context, in *DirScanRequest, opts ...grpc.CallOption) (*DirScanResponse, error) {
	out := new(DirScanResponse)
	err := c.cc.Invoke(ctx, "/server.Dirscanner/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirscannerServer is the server API for Dirscanner service.
// All implementations must embed UnimplementedDirscannerServer
// for forward compatibility
type DirscannerServer interface {
	Scan(context.Context, *DirScanRequest) (*DirScanResponse, error)
	mustEmbedUnimplementedDirscannerServer()
}

// UnimplementedDirscannerServer must be embedded to have forward compatible implementations.
type UnimplementedDirscannerServer struct {
}

func (UnimplementedDirscannerServer) Scan(context.Context, *DirScanRequest) (*DirScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedDirscannerServer) mustEmbedUnimplementedDirscannerServer() {}

// UnsafeDirscannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirscannerServer will
// result in compilation errors.
type UnsafeDirscannerServer interface {
	mustEmbedUnimplementedDirscannerServer()
}

func RegisterDirscannerServer(s grpc.ServiceRegistrar, srv DirscannerServer) {
	s.RegisterService(&Dirscanner_ServiceDesc, srv)
}

func _Dirscanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirscannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Dirscanner/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirscannerServer).Scan(ctx, req.(*DirScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dirscanner_ServiceDesc is the grpc.ServiceDesc for Dirscanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dirscanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.Dirscanner",
	HandlerType: (*DirscannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _Dirscanner_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/server/proto/dirscanner.proto",
}
